name: Add issues to Cross-Bot Hotlist
on:
  issues:
    types: [opened, reopened, labeled, edited, transferred]

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - name: Add to user project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/cailleanC1C/projects/1
          github-token: ${{ secrets.PROJECTS_TOKEN }}
          content-id: ${{ github.event.issue.node_id }}
