name: feature-setup-shards-mercy

on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          script-path: .github/scripts/feature-setup-shards-mercy.js

