name: feature-setup-shards-mercy

on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run prefilled setup script
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = '.github/scripts/feature-setup-shards-mercy.js';
            const code = fs.readFileSync(path, 'utf8');
            // Execute the file as an async function so top-level awaits work
            const AsyncFunction = Object.getPrototypeOf(async function(){}).constructor;
            const run = new AsyncFunction('github','context','core', code);
            await run(github, context, core);
